trigger:
  - master_frontend

pool:
  vmImage: 'ubuntu-18.04'
variables:
  dockerRegistryServiceConnection: 'UNICEF_DATA_CONNECT_WEB_ACR'
  dockerfilePath: './Dockerfile'
  app: 'project-connect-frontend'
  imageRepository: 'dev/$(app)'
  tag: '$(Build.BuildId)'

steps:
  # Docker build and push
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      arguments: --build-arg=API_BASE_URL=$(apiBaseUrl) --build-arg=API_MAPBOX_ACCESS_TOKEN=$(mapboxToken)
      tags: |
        $(tag)
  - task: Docker@2
    displayName: Push image to container registry
    inputs:
      command: push
      repository: $(imageRepository)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
