trigger:
  - master_frontend

pool:
  vmImage: 'ubuntu-18.04'
variables:
  dockerRegistryServiceConnection: 'UNICEF_DATA_CONNECT_WEB_ACR'
  dockerfilePath: './Dockerfile'
  app: 'project-connect-frontend'
  imageRepository: 'dev/$(app)'
  tag: '$(Build.BuildId)'
  mapboxToken: 'test'
  apiBaseUrl: 'https://api.projectconnect.razortheory.com/'

steps:
  # Docker build and push
  - task: Docker@2
    displayName: Build and push image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      arguments: --build-arg=API_BASE_URL=$(apiBaseUrl) --build-arg=API_MAPBOX_ACCESS_TOKEN=$(mapboxToken)
      tags: |
        $(tag)
